# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --region us-west-2 --stack-name my-stack
jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: 
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --region us-west-2 \
              --template-file template.yml \
              --stack-name my-stack
      - run: return 1
      - run: 
          name: rollback_on_failure
          command: destroy_environment
          when: on_fail
workflows:
  my_workflow:
    jobs:
      - create_infrastructure
    
